import Head from 'next/head'
import Header from '../components/Header'
import Main from '../components/Main'

export default function Home({ creatures }) {
  return (
    // Overflow hidden is amazing !!!
    <div className='bg-image min-h-screen flex flex-col items-center relative overflow-hidden'>
      <Head>
        <title>Roll For Initiative</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/d20-holo.png" />
      </Head>

      <Header />
      <Main 
        creatures={creatures}
      />
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://www.dnd5eapi.co/api/monsters');
  const json = await res.json();
  const creatures = json.results;

  return {
    props: {
      creatures
    },
  }
}