import Head from 'next/head'
import { useEffect, useRef } from 'react'
import { useRecoilState } from 'recoil'
import { loadingState } from '../atoms/loadingAtom'
import { monsterManualState } from '../atoms/monsterManualAtom'
import Header from '../components/Header'
import Loader from '../components/Loader'
import Main from '../components/Main'
import MonsterManual from '../components/MonsterManual'
import { Transition } from '@headlessui/react'

export default function Home({ creatures }) {
  const [isLoading] = useRecoilState(loadingState)
  const [monsterManualOpen, setMonsterManualOpen] = useRecoilState(monsterManualState)
  // This stuff is to prevent input scrolling from scrolling the body
  const ref = useRef(null)

  useEffect(() => {
    const reff = ref.current
    const wheelHandler = () => {}
    reff.addEventListener('wheel', wheelHandler)
    return () => reff.removeEventListener('wheel', wheelHandler)
  }, [ref])
  
  return (
    // Overflow hidden is amazing !!!
    <div 
      className='bg-image min-h-screen flex flex-col items-center relative overflow-hidden'
      ref={ref}
    >
      <Head>
        <title>Roll For Initiative</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/d20-holo.png" />
      </Head>

      <Header />

      <Main 
        creatures={creatures}
      />

      {/* Monster Manual */}
      <Transition
        show={monsterManualOpen}
        enter="transition-all duration-300"
        enterFrom="opacity-0 ease-in scale-0"
        enterTo="opacity-100 scale-100"
        leave="transition-all ease-out duration-300"
        leaveFrom="opacity-100 scale-100"
        leaveTo="opacity-0 scale-0"
        className='fixed w-screen height-minus-header mm-bg p-6 flex justify-center'
      >
        <MonsterManual 
          creatures={creatures}
        />
      </Transition>

      {/* Loading spinner */}
      {/* {
        isLoading  && <Loader />
      } */}
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://www.dnd5eapi.co/api/monsters');
  const json = await res.json();
  const creatures = json.results;

  return {
    props: {
      creatures
    },
  }
}